FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm install --legacy-peer-deps
COPY . .
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
# prod.nginx.conf for pushing to ghcr, dev.nginx.conf for local docker compose.
COPY prod.nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 7080
EXPOSE 7443
CMD ["nginx", "-g", "daemon off;"]
