services:
  api:
    image: ghcr.io/sunba23/mpkiso-api:latest
    environment:
      REDIS_URL: redis:6379
      PG_HOST: host.docker.internal
    ports:
      - "8080:8080"
    extra_hosts:
      - host.docker.internal:host-gateway
    secrets:
      - REDIS_PASSWORD
      - PG_DBNAME
      - PG_USER
      - PG_PASSWORD
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: on-failure
    networks:
      - mpkisonet

  redis:
    image: redis:7.4
    secrets:
      - REDIS_PASSWORD
    volumes:
      - redis-data:/data
    command: sh -c "redis-server --bind 0.0.0.0 --maxmemory 500mb --requirepass $$(cat /run/secrets/REDIS_PASSWORD)"
    deploy:
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
    networks:
      - mpkisonet

  frontend:
    image: ghcr.io/sunba23/mpkiso-frontend:latest
    ports:
      - "7080:7080"
      - "7443:7443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: on-failure
    networks:
      - mpkisonet

networks:
  mpkisonet:
    driver: overlay

secrets:
  REDIS_PASSWORD:
    external: true
  PG_PASSWORD:
    external: true
  PG_USER:
    external: true
  PG_DBNAME:
    external: true

volumes:
  redis-data:
    driver: local
