[project]
name = "gtfs-importer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "psycopg>=3.2.4",
    "requests>=2.32.3",
    "rich>=13.9.4",
]
